# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{artisan}
  s.version = "0.3.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{patrickgombert cymen benthebossvoss}]
  s.date = %q{2011-10-06}
  s.description = %q{Make calls to the Artisan API.}
  s.email = %q{patrick@8thlight.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "artisan.gemspec",
    "lib/artisan.rb",
    "lib/artisan/base.rb",
    "lib/artisan/project.rb",
    "lib/artisan/iteration.rb",
    "lib/artisan/query.rb",
    "lib/artisan/story.rb",
    "lib/artisan/signoff_pdf.rb",
    "spec/artisan/project_spec.rb",
    "spec/artisan/iteration_spec.rb",
    "spec/artisan/story_spec.rb",
    "spec/artisan/validation_spec.rb",
    "spec/artisan/signoff_pdf_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{https://github.com/8thlight/artisan_api}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Artisan API wrapper}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, ["~> 0.8.3"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_development_dependency(%q<cucumber>, ["~> 1.0.2"])
      s.add_runtime_dependency(%q<httparty>, ["~> 0.8.3"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, ["~> 0.8.3"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_dependency(%q<cucumber>, ["~> 1.0.2"])
      s.add_dependency(%q<httparty>, ["~> 0.8.3"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, ["~> 0.8.3"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.1.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.6.0"])
    s.add_dependency(%q<cucumber>, ["~> 1.0.2"])
    s.add_dependency(%q<httparty>, ["~> 0.8.3"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

